org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:/Users/DMills/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2

# Mod version and naming
mod_id=bulk_crafting
mod_name=Create: Bulk Crafting
mod_version=1.0.1
mod_group_id=com.jokrisbest.bulk_crafting
mod_authors=DMills
mod_description=A Create addon that allows mixing and compacting in basins to process large batches of ingredients in a single operation cycle.

# Dependencies
minecraft_version=1.21.1
neo_version=21.1.219
create_version=6.0.10
